"""
CHORA — GRU predictive model training.

Training data is generated by the TypeScript PulseGenerator (the single source
of truth for signal math) and consumed here as a plain CSV.

Prerequisites:
  1. Build @chora/core:    cd packages/core && pnpm build
  2. Generate CSV:         node scripts/generate-training-data.mjs
  3. Train (this script):  cd packages/training && python train.py
"""

import os
import sys

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# Reproducibility
np.random.seed(42)
torch.manual_seed(42)

# ---------------------------------------------------------------------------
# Load data from CSV generated by generate-training-data.mjs
# ---------------------------------------------------------------------------
CSV_PATH = os.path.join(os.path.dirname(__file__), "data", "pulses.csv")

if not os.path.exists(CSV_PATH):
    print(
        f"ERROR: Training data not found at:\n  {CSV_PATH}\n\n"
        "Please generate it first by running (from the repo root):\n"
        "  node scripts/generate-training-data.mjs",
        file=sys.stderr,
    )
    sys.exit(1)

print(f"Loading training data from: {CSV_PATH}")
data = np.loadtxt(CSV_PATH, delimiter=",", dtype=np.float32)
print(f"Loaded {len(data):,} rows, shape {data.shape}")


# ---------------------------------------------------------------------------
# GRU model definition (unchanged from original)
# ---------------------------------------------------------------------------
class PredictorGRU(nn.Module):
    def __init__(self, input_size=4, hidden_size=16, num_layers=1, output_size=4):
        super(PredictorGRU, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        out, _ = self.gru(x, h0)
        out = self.fc(out[:, -1, :])
        return out


def main():
    # Create sliding windows of size 32
    window_size = 32
    X = []
    Y = []
    for i in range(len(data) - window_size):
        X.append(data[i : i + window_size])
        Y.append(data[i + window_size])

    X = np.array(X)
    Y = np.array(Y)

    # Train/Val split
    split = int(len(X) * 0.9)
    X_train, X_val = X[:split], X[split:]
    Y_train, Y_val = Y[:split], Y[split:]

    # Convert to PyTorch tensors
    X_train_tensor = torch.tensor(X_train)
    Y_train_tensor = torch.tensor(Y_train)
    X_val_tensor = torch.tensor(X_val)
    Y_val_tensor = torch.tensor(Y_val)

    # Model, loss, optimizer
    model = PredictorGRU()
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.005)

    batch_size = 128
    epochs = 5

    print("Training the GRU model...")
    for epoch in range(epochs):
        model.train()
        permutation = torch.randperm(X_train_tensor.size(0))
        epoch_loss = 0.0

        for i in range(0, X_train_tensor.size(0), batch_size):
            indices = permutation[i : i + batch_size]
            batch_x, batch_y = X_train_tensor[indices], Y_train_tensor[indices]

            optimizer.zero_grad()
            predictions = model(batch_x)
            loss = criterion(predictions, batch_y)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * batch_x.size(0)

        epoch_loss /= X_train_tensor.size(0)

        # Validation loss
        model.eval()
        with torch.no_grad():
            val_preds = model(X_val_tensor)
            val_loss = criterion(val_preds, Y_val_tensor).item()

        print(
            f"Epoch {epoch+1}/{epochs} | Train Loss: {epoch_loss:.6f} | Val Loss: {val_loss:.6f}"
        )

    # Export to ONNX
    print("Exporting model to ONNX...")
    models_dir = "../../models"
    os.makedirs(models_dir, exist_ok=True)
    onnx_path = os.path.join(models_dir, "predictive_model.onnx")

    # Example input representing dynamic batch size
    dummy_input = torch.randn(1, window_size, 4)

    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        export_params=True,
        opset_version=18,
        dynamo=False,  # use TorchScript path; avoids onnxscript unicode-emoji issue
        do_constant_folding=True,
        input_names=["input"],
        output_names=["output"],
        dynamic_axes={"input": {0: "batch_size"}, "output": {0: "batch_size"}},
    )
    print(f"Model successfully exported to: {os.path.abspath(onnx_path)}")


if __name__ == "__main__":
    main()
